// <auto-generated />
namespace B2WTI.PCFTI.INFRAESTRUTURA.HORIZONTAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PCFTIDB0002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PCFTIDB0002));
        
        string IMigrationMetadata.Id
        {
            get { return "201504012033474_PCFTIDB0002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
